--------------------------------------------------------
-- Archivo creado  - lunes-noviembre-27-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AVION
--------------------------------------------------------

  CREATE TABLE "JUAN"."AVION" 
   (	"AVI_MATRICULA" VARCHAR2(10 BYTE), 
	"AVI_MODELO" NUMBER(*,0), 
	"AVI_NUM_SILLAS" NUMBER(*,0), 
	"AVI_UBICACION" VARCHAR2(30 BYTE), 
	"AVI_ESTADO" VARCHAR2(10 BYTE) DEFAULT 'DISPONIBLE'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table AVION_VUELO
--------------------------------------------------------

  CREATE TABLE "JUAN"."AVION_VUELO" 
   (	"AVI_MATRICULA" VARCHAR2(10 BYTE), 
	"VUE_NUM_REF" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "JUAN"."EMPLEADO" 
   (	"PER_CEDULA" VARCHAR2(15 BYTE), 
	"EMP_SALARIO" NUMBER(*,0), 
	"EMP_TIPO_CARGO" VARCHAR2(20 BYTE), 
	"EMP_ESTADO" VARCHAR2(15 BYTE) DEFAULT 'ACTIVO'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO_VUELO
--------------------------------------------------------

  CREATE TABLE "JUAN"."EMPLEADO_VUELO" 
   (	"PER_CEDULA" VARCHAR2(15 BYTE), 
	"VUE_NUM_REF" NUMBER(*,0), 
	"EV_CANT_PASAJEROS" NUMBER(*,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "JUAN"."PERSONA" 
   (	"PER_CEDULA" VARCHAR2(15 BYTE), 
	"PER_NOMBRE" VARCHAR2(20 BYTE), 
	"PER_APELLIDO" VARCHAR2(20 BYTE), 
	"PER_NACIONALIDAD" VARCHAR2(20 BYTE), 
	"PER_DIRECCION" VARCHAR2(70 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA_VUELO
--------------------------------------------------------

  CREATE TABLE "JUAN"."PERSONA_VUELO" 
   (	"PER_CEDULA" VARCHAR2(15 BYTE), 
	"VUE_NUM_REF" NUMBER(*,0), 
	"PV_FECHA_RES" DATE DEFAULT SYSDATE, 
	"PV_SILLA" VARCHAR2(5 BYTE), 
	"PV_COD_RESERVA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PILOTO
--------------------------------------------------------

  CREATE TABLE "JUAN"."PILOTO" 
   (	"PER_CEDULA" VARCHAR2(15 BYTE), 
	"PIL_LICENCIA" VARCHAR2(20 BYTE), 
	"PIL_CATEGORIA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VUELO
--------------------------------------------------------

  CREATE TABLE "JUAN"."VUELO" 
   (	"VUE_NUM_REF" NUMBER(*,0), 
	"VEU_FECHA" DATE, 
	"VUE_DURACION" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"VUE_AP_SALIDA" VARCHAR2(30 BYTE), 
	"VUE_AP_LLEGADA" VARCHAR2(30 BYTE), 
	"VUE_MILLAS" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into JUAN.AVION
SET DEFINE OFF;
Insert into JUAN.AVION (AVI_MATRICULA,AVI_MODELO,AVI_NUM_SILLAS,AVI_UBICACION,AVI_ESTADO) values ('asd','23','23','safsdf','DISPONIBLE');
Insert into JUAN.AVION (AVI_MATRICULA,AVI_MODELO,AVI_NUM_SILLAS,AVI_UBICACION,AVI_ESTADO) values ('erer','23','32','colombia','DISPONIBLE');
REM INSERTING into JUAN.AVION_VUELO
SET DEFINE OFF;
REM INSERTING into JUAN.EMPLEADO
SET DEFINE OFF;
REM INSERTING into JUAN.EMPLEADO_VUELO
SET DEFINE OFF;
REM INSERTING into JUAN.PERSONA
SET DEFINE OFF;
Insert into JUAN.PERSONA (PER_CEDULA,PER_NOMBRE,PER_APELLIDO,PER_NACIONALIDAD,PER_DIRECCION) values ('asd','asd','asds','COLOMBIA','asdsd');
REM INSERTING into JUAN.PERSONA_VUELO
SET DEFINE OFF;
REM INSERTING into JUAN.PILOTO
SET DEFINE OFF;
REM INSERTING into JUAN.VUELO
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."EMPLEADO_PK" ON "JUAN"."EMPLEADO" ("PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index VUELO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."VUELO_PK" ON "JUAN"."VUELO" ("VUE_NUM_REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_VUELO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."EMPLEADO_VUELO_PK" ON "JUAN"."EMPLEADO_VUELO" ("PER_CEDULA", "VUE_NUM_REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PILOTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."PILOTO_PK" ON "JUAN"."PILOTO" ("PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index AVION_VUELO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."AVION_VUELO_PK" ON "JUAN"."AVION_VUELO" ("AVI_MATRICULA", "VUE_NUM_REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_AVION
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."PK_AVION" ON "JUAN"."AVION" ("AVI_MATRICULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_VUELO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."PERSONA_VUELO_PK" ON "JUAN"."PERSONA_VUELO" ("PER_CEDULA", "VUE_NUM_REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "JUAN"."PERSONA_PK" ON "JUAN"."PERSONA" ("PER_CEDULA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table AVION
--------------------------------------------------------

  ALTER TABLE "JUAN"."AVION" ADD CONSTRAINT "PK_AVION" PRIMARY KEY ("AVI_MATRICULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."AVION" ADD CONSTRAINT "CKC_ESTADO_AVION" CHECK (AVI_ESTADO in ('DISPONIBLE','OCUPADO','REPARACION')) ENABLE;
  ALTER TABLE "JUAN"."AVION" MODIFY ("AVI_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."AVION" MODIFY ("AVI_NUM_SILLAS" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."AVION" MODIFY ("AVI_MODELO" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."AVION" MODIFY ("AVI_MATRICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA_VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."PERSONA_VUELO" ADD CONSTRAINT "PERSONA_VUELO_PK" PRIMARY KEY ("PER_CEDULA", "VUE_NUM_REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."PERSONA_VUELO" MODIFY ("PV_COD_RESERVA" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."PERSONA_VUELO" MODIFY ("VUE_NUM_REF" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."PERSONA_VUELO" MODIFY ("PER_CEDULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PILOTO
--------------------------------------------------------

  ALTER TABLE "JUAN"."PILOTO" ADD CONSTRAINT "PILOTO_PK" PRIMARY KEY ("PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."PILOTO" MODIFY ("PIL_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."PILOTO" MODIFY ("PIL_LICENCIA" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."PILOTO" MODIFY ("PER_CEDULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "JUAN"."PERSONA" ADD CONSTRAINT "CKC_NACIONALIDAD_EMPLEADO" CHECK (PER_NACIONALIDAD in ('COLOMBIA','PERU','CHILE','ARGENTINA','MEXICO')) ENABLE;
  ALTER TABLE "JUAN"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."PERSONA" MODIFY ("PER_APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."PERSONA" MODIFY ("PER_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."PERSONA" MODIFY ("PER_CEDULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AVION_VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."AVION_VUELO" ADD CONSTRAINT "AVION_VUELO_PK" PRIMARY KEY ("AVI_MATRICULA", "VUE_NUM_REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."AVION_VUELO" MODIFY ("VUE_NUM_REF" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."AVION_VUELO" MODIFY ("AVI_MATRICULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO_VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."EMPLEADO_VUELO" ADD CONSTRAINT "EMPLEADO_VUELO_PK" PRIMARY KEY ("PER_CEDULA", "VUE_NUM_REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."EMPLEADO_VUELO" MODIFY ("VUE_NUM_REF" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."EMPLEADO_VUELO" MODIFY ("PER_CEDULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."VUELO" ADD CONSTRAINT "VUELO_PK" PRIMARY KEY ("VUE_NUM_REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."VUELO" MODIFY ("VUE_MILLAS" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."VUELO" MODIFY ("VUE_AP_LLEGADA" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."VUELO" MODIFY ("VUE_AP_SALIDA" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."VUELO" MODIFY ("VEU_FECHA" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."VUELO" MODIFY ("VUE_NUM_REF" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "JUAN"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("PER_CEDULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "JUAN"."EMPLEADO" ADD CONSTRAINT "CKC_ESTAD O_EMPLEADO" CHECK (EMP_ESTADO in ('ADMINISTRATIVO','PILOTO','TCP')) ENABLE;
  ALTER TABLE "JUAN"."EMPLEADO" MODIFY ("EMP_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."EMPLEADO" MODIFY ("EMP_TIPO_CARGO" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."EMPLEADO" MODIFY ("EMP_SALARIO" NOT NULL ENABLE);
  ALTER TABLE "JUAN"."EMPLEADO" MODIFY ("PER_CEDULA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table AVION_VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."AVION_VUELO" ADD CONSTRAINT "AVION_VUELO_FK1" FOREIGN KEY ("AVI_MATRICULA")
	  REFERENCES "JUAN"."AVION" ("AVI_MATRICULA") ENABLE;
  ALTER TABLE "JUAN"."AVION_VUELO" ADD CONSTRAINT "AVION_VUELO_FK2" FOREIGN KEY ("VUE_NUM_REF")
	  REFERENCES "JUAN"."VUELO" ("VUE_NUM_REF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "JUAN"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_FK1" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "JUAN"."PERSONA" ("PER_CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO_VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."EMPLEADO_VUELO" ADD CONSTRAINT "EMPLEADO_VUELO_FK1" FOREIGN KEY ("VUE_NUM_REF")
	  REFERENCES "JUAN"."VUELO" ("VUE_NUM_REF") ENABLE;
  ALTER TABLE "JUAN"."EMPLEADO_VUELO" ADD CONSTRAINT "EMPLEADO_VUELO_FK2" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "JUAN"."EMPLEADO" ("PER_CEDULA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERSONA_VUELO
--------------------------------------------------------

  ALTER TABLE "JUAN"."PERSONA_VUELO" ADD CONSTRAINT "PERSONA_VUELO_FK1" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "JUAN"."PERSONA" ("PER_CEDULA") ENABLE;
  ALTER TABLE "JUAN"."PERSONA_VUELO" ADD CONSTRAINT "PERSONA_VUELO_FK2" FOREIGN KEY ("VUE_NUM_REF")
	  REFERENCES "JUAN"."VUELO" ("VUE_NUM_REF") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PILOTO
--------------------------------------------------------

  ALTER TABLE "JUAN"."PILOTO" ADD CONSTRAINT "PILOTO_FK1" FOREIGN KEY ("PER_CEDULA")
	  REFERENCES "JUAN"."EMPLEADO" ("PER_CEDULA") ENABLE;
